name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.1'
        use-public-rspm: true
        

    - name: Install R dependencies
      run: |
        R -e "install.packages(c('ggplot2', 'mosaic', 'tidyverse', 'dplyr', 'lintr'), repos='http://cran.rstudio.com/')"

    - name: Lint R code
      run: |
        R -e 'lintr::lint_dir(path = "R")'
          
    - name: Run R script
      run: |
        Rscript CI-Analysis.R

    - name: ZIP code
      run: |
        zip -r code.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: code-artifact
        path: code.zip
